[package]
name = "icebreaker"
version = "0.1.0"
authors = ["Héctor Ramón Jiménez <hector@hecrj.dev>"]
edition = "2021"
publish = false

[dependencies]
iced.version = "0.13"
iced.features = ["tokio", "svg", "markdown", "highlighter", "system", "web-colors", "debug"]

tokio.version = "1.38"
tokio.features = ["fs", "io-util", "process", "time"]

tokio-stream.version = "0.1"
tokio-stream.features = ["io-util"]

reqwest.version = "0.12"
reqwest.features = ["json"]

serde.version = "1.0"
serde.features = ["derive"]

chrono.version = "0.4"
chrono.features = ["serde"]

uuid.version = "1.10"
uuid.features = ["v4", "serde"]

dirs-next = "2.0"
futures = "0.3"
itertools = "0.13"
open = "5.2"
serde_json = "1.0"
thiserror = "1.0"
